"""Context-dependent quotes

Revision ID: 2919d38e7195
Revises: d47476a83db8
Create Date: 2022-09-02 01:26:08.637121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2919d38e7195'
down_revision = 'd47476a83db8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quote', sa.Column('context', sa.String(length=128), nullable=True))
    op.add_column('quote', sa.Column('local_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quote', 'local_id')
    op.drop_column('quote', 'context')
    # ### end Alembic commands ###
