"""Quotes and clip monitoring

Revision ID: d47476a83db8
Revises: 
Create Date: 2022-09-01 15:40:22.208617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd47476a83db8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('author',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('_type', sa.Enum('NONE', 'TWITCH', name='eauthortype'), nullable=True),
    sa.Column('last_checked', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quote',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('quote_text', sa.Text(), nullable=True),
    sa.Column('added_by', sa.String(length=128), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('video',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('_type', sa.Enum('VIDEO', 'TWITCH_CLIP', 'TWITCH_VIDEO', name='evideotype'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('filename', sa.String(length=256), nullable=True),
    sa.Column('directory', sa.String(length=256), nullable=True),
    sa.Column('download_status', sa.Enum('DO_NOT_DOWNLOAD', 'PENDING', 'IN_PROGRESS', 'DONE', name='edownloadstatus'), nullable=True),
    sa.Column('online', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('twitch_broadcaster',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('login', sa.String(length=64), nullable=False),
    sa.Column('profile_image_url', sa.String(length=256), nullable=True),
    sa.Column('broadcaster_type', sa.String(length=32), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['author.id'], ),
    sa.PrimaryKeyConstraint('id', 'external_id', 'login')
    )
    op.create_index(op.f('ix_twitch_broadcaster_external_id'), 'twitch_broadcaster', ['external_id'], unique=False)
    op.create_table('video_author',
    sa.Column('video_id', sa.Integer(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['author.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['video.id'], )
    )
    op.create_table('twitch_video',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('duration', sa.String(length=32), nullable=True),
    sa.Column('language', sa.String(length=32), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=256), nullable=True),
    sa.Column('type', sa.String(length=32), nullable=True),
    sa.Column('broadcaster_id', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['broadcaster_id'], ['twitch_broadcaster.external_id'], ),
    sa.ForeignKeyConstraint(['id'], ['video.id'], ),
    sa.PrimaryKeyConstraint('id', 'external_id')
    )
    op.create_index(op.f('ix_twitch_video_external_id'), 'twitch_video', ['external_id'], unique=False)
    op.create_table('twitch_clip',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=256), nullable=False),
    sa.Column('broadcaster_id', sa.Integer(), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('video_id', sa.Integer(), nullable=True),
    sa.Column('duration', sa.String(length=32), nullable=True),
    sa.Column('language', sa.String(length=32), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=256), nullable=True),
    sa.Column('vod_offset', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['broadcaster_id'], ['twitch_broadcaster.external_id'], ),
    sa.ForeignKeyConstraint(['creator_id'], ['twitch_broadcaster.external_id'], ),
    sa.ForeignKeyConstraint(['id'], ['video.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['twitch_video.external_id'], ),
    sa.PrimaryKeyConstraint('id', 'external_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('twitch_clip')
    op.drop_index(op.f('ix_twitch_video_external_id'), table_name='twitch_video')
    op.drop_table('twitch_video')
    op.drop_table('video_author')
    op.drop_index(op.f('ix_twitch_broadcaster_external_id'), table_name='twitch_broadcaster')
    op.drop_table('twitch_broadcaster')
    op.drop_table('video')
    op.drop_table('quote')
    op.drop_table('author')
    # ### end Alembic commands ###
